{{-- Shared letter chrome: mirror of the header / student strip / QR box in
     components/transfers/letter-article.tsx & withdrawal-letter-article.tsx.
     Expects: $school, $branch, $reference, $letterTitle, $student (array),
     $slotDl (rendered <dl> HTML), $signLabel, $signName, $signDate, $qr,
     optional $noteHtml. --}}
@php
  $initials = collect(explode(' ', (string) ($student['full_name'] ?? '')))
      ->filter()->take(2)->map(fn ($p) => mb_strtoupper(mb_substr($p, 0, 1)))->implode('');
@endphp

<article class="card">
  {{-- header --}}
  <div class="card-header" style="padding-bottom:24px">
    <div>
      <h2 class="font-display" style="font-size:20px; font-weight:600">{{ $school }}</h2>
      <p class="muted" style="font-size:14px">{{ $branch }}</p>
    </div>
    <div style="text-align:right">
      @include('documents.partials.brand')
      <p class="muted tnum" style="margin-top:4px; font-size:12px">Ref {{ $reference }}</p>
    </div>
  </div>

  <h1 class="font-display" style="margin-top:32px; text-align:center; font-size:18px; font-weight:600; letter-spacing:-0.025em">
    {{ $letterTitle }}
  </h1>

  {{-- student strip: PersonAvatar size-16 + name + id · dob --}}
  <div style="margin-top:32px; display:flex; align-items:center; gap:16px">
    <span style="width:64px; height:64px; border-radius:9999px; overflow:hidden; flex-shrink:0;
                 display:flex; align-items:center; justify-content:center;
                 background:oklch(0.47 0.115 155 / 0.1); color:var(--primary);
                 font-size:18px; font-weight:600">
      @if (! empty($student['photo_url']))
        <img src="{{ $student['photo_url'] }}" alt="" style="width:100%; height:100%; object-fit:cover">
      @else
        {{ $initials ?: '?' }}
      @endif
    </span>
    <div>
      <p style="font-size:18px; font-weight:600">{{ $student['full_name'] }}</p>
      <p class="muted tnum" style="font-size:14px">
        Student ID: {{ $student['public_id'] ?? '—' }}@if (! empty($student['date_of_birth'])) · Date of birth: {{ dualDate($student['date_of_birth']) }}@endif
      </p>
    </div>
  </div>

  {{-- facts grid --}}
  <dl style="margin-top:32px; display:grid; grid-template-columns:1fr 1fr; column-gap:32px; row-gap:16px; font-size:14px">
    {!! $slotDl !!}
  </dl>

  {!! $noteHtml ?? '' !!}

  {{-- sign-off --}}
  <div style="margin-top:48px; display:flex; align-items:flex-end; justify-content:space-between; gap:24px; border-top:1px solid var(--border); padding-top:24px; font-size:14px">
    <div>
      <p class="microlabel">{{ $signLabel }}</p>
      <p style="margin-top:4px; font-weight:500">{{ $signName ?? '—' }}</p>
      <div style="margin-top:24px; height:1px; width:160px; background:var(--border)"></div>
    </div>
    <div style="text-align:right">
      <p class="microlabel">Date</p>
      <p class="tnum" style="margin-top:4px; font-weight:500">{{ $signDate ?? '—' }}</p>
    </div>
  </div>

  {{-- verification box --}}
  <div style="margin-top:32px; display:flex; align-items:center; gap:16px; border:1px dashed var(--border); border-radius:12px; padding:12px">
    <img src="{{ $qr }}" alt="QR" style="width:80px; height:80px; flex-shrink:0; border-radius:6px; background:#fff">
    <div style="min-width:0; text-align:left">
      <p style="font-size:12px; font-weight:500">Scan to verify this letter online</p>
      <p class="muted" style="margin-top:2px; font-size:11px">
        Generated by Temari.et — verifiable against reference {{ $reference }}.
      </p>
    </div>
  </div>
</article>
