export default {
    key: 'onboarding',
    label: 'Welcome to FINOTE Admin',
    description: 'Get started with full administrative access to the FINOTE CMS.',
    steps: [
        {
            key: 'sidebar-welcome',
            selector: '[data-tour="sidebar"]',
            title: 'Navigation Sidebar',
            description: 'This is your main navigation panel. All sections are accessible from here. Use the collapsible groups to find what you need.',
            side: 'right',
            align: 'center',
        },
        {
            key: 'dashboard-link',
            selector: '[data-tour="dashboard-link"]',
            title: 'Dashboard',
            description: 'Your command center. View real-time metrics, charts, and quick insights about your organization.',
            side: 'right',
            align: 'start',
        },
        {
            key: 'members-section',
            selector: '[data-tour="members-section"]',
            title: 'Members Management',
            description: 'Manage all church members, their profiles, family relationships, and enrollment in educational programs.',
            side: 'right',
            align: 'start',
        },
        {
            key: 'finance-section',
            selector: '[data-tour="finance-section"]',
            title: 'Financial Management',
            description: 'Track donations, contributions, financial reports, and manage revenue & banking operations.',
            side: 'right',
            align: 'start',
        },
        {
            key: 'education-section',
            selector: '[data-tour="education-section"]',
            title: 'Education Management',
            description: 'Manage classes, subjects, teacher assignments, student enrollments, and track attendance.',
            side: 'right',
            align: 'start',
        },
        {
            key: 'system-section',
            selector: '[data-tour="system-section"]',
            title: 'System Administration',
            description: 'Configure users, roles, permissions, backups, and system settings. Superadmin-only access.',
            side: 'right',
            align: 'start',
        },
        {
            key: 'user-menu',
            selector: '[data-tour="user-menu"]',
            title: 'User Menu',
            description: 'Access your profile, manage sessions, and sign out. Use "Restart Tour" to revisit this guide anytime.',
            side: 'bottom',
            align: 'end',
        },
        {
            key: 'completion',
            selector: '[data-tour="dashboard-content"]',
            title: 'You\'re All Set!',
            description: 'You now have a complete overview of the FINOTE admin panel. Explore each section to dive deeper. Need help? Restart this tour from the user menu anytime.',
            side: 'bottom',
            align: 'center',
        },
    ],
};
